server:
  port: 8090
  context-path: /girl
girl: #HelloController里用到
  cupSize: C
  age: 19
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/girl
    username: root
    password:
  jpa:
    hibernate:
    #自动创建
      ddl-auto: none
    show-sql: true

